config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
  get 'signup', to: 'users#new'
  resources :users, param: :friendly_id, only: %i[show create edit update destroy] do
    member do
      get :followings
      get :followers
      get :favorite_articles
      get :introduction
    end
  end
  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :articles, only: [:destroy] do
      collection do
        get :spams
      end
    end 
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  
  resources :articles, only: %i[show new create destroy] do
    collection do
      get :timeline
      get :favorite_articles
      get :tagged_articles
      get :monthly_ranking
    end

    resources :comments, only: [:create]
  end
  
  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :tags, only: [:show]
  resources :tag_follows, only: %i[create destroy]
  resources :searches, only: [:index]
  resources :report_spams, only: %i[create destroy]
  resources :oembed, only: [:create]
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  belongs_to :user
  has_many :oembed, class_name: 'ActionText::Oembed', dependent: :destroy

  has_many :reverses_of_favorite, class_name: 'Favorite', dependent: :destroy
  has_many :liked_users, through: :reverses_of_favorite, source: :user
  
  has_many :reverses_of_report_spam, class_name: 'ReportSpam', dependent: :destroy
  has_many :reported_users, through: :reverses_of_report_spam, source: :user
  
  has_many :reverses_of_tag_maps, class_name: 'TagMap', dependent: :destroy
  has_many :attached_tags, through: :reverses_of_tag_maps, source: :tag

  has_many :comments, dependent: :destroy
  
  scope :search, ->(search) { where(['title LIKE ?', "%#{search}%"]) if search.present? }
  scope :feed, ->(user) { where("user_id IN (?) OR user_id = ?", user.following_ids, user.id) }
  
  def self.ranking(monthly_articles)
    articles = monthly_articles.sort { |a, b| b.liked_users.count <=> a.liked_users.count }
    monthly_ranking_articles = articles.last(10)
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  include CommonActions
  before_action :admin_user
  
  def spams
    spams = ReportSpam.all.preload(article: [:attached_tags, user: { image_attachment: :blob }])
    spam_articles = ReportSpam.spam_articles(spams)
    @spam_articles = Kaminari.paginate_array(spam_articles).page(params[:page])
  end
  
  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to spams_admin_articles_url
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include CommonActions
  before_action :require_user_logged_in, only: %i[new create destroy timeline favorite_articles tagged_articles]
  before_action :correct_user, only: %i[destroy]
  
  def index
    @user = User.new
    @articles = Article.page(params[:page]).order(created_at: :desc).preload(:attached_tags, user: { image_attachment: :blob })
  end
  
  def show
    @article = Article.find(params[:id])
    @user = @article.user
    @count_favorites = @article.liked_users.count
    @comments = @article.comments
    @comment = Comment.new
  end

  def new
    @form = ArticleForm.new
  end

  def create
    @form = ArticleForm.new(article_params)
    if @form.save
      flash[:success] = '記事を投稿しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '記事の投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @article.destroy
    flash[:success] = '記事を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def timeline
    @articles = Article.feed(current_user).page(params[:page]).order(created_at: :desc).preload(:attached_tags, user: { image_attachment: :blob })
  end
  
  def favorite_articles
    @articles = current_user.favorite_articles.page(params[:page]).order(created_at: :desc).preload(:attached_tags, user: { image_attachment: :blob })
  end
  
  def tagged_articles
    articles = current_user.following_tags.preload(tagged_articles: [:attached_tags, user: { image_attachment: :blob }]).map { |o| o.tagged_articles.to_ary }.flatten.uniq.sort.reverse
    @articles = Kaminari.paginate_array(articles).page(params[:page])
  end

  def monthly_ranking
    monthly_articles = Article.where(updated_at: Time.zone.today.all_month).preload(:attached_tags, user: { image_attachment: :blob })
    @monthly_ranking_articles = Article.ranking(monthly_articles)
  end
  
  private
  
  def article_params
    params.require(:article).permit(:title, :content, :tag_names).merge(user_id: current_user.id)
  end
  
  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    return if @article

    redirect_to root_url
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_feed.html.erb
<div>記事フィード</div>
<ul>
  <li><%= link_to '最新', root_path %></li>
  <% if logged_in? %>
    <li><%= link_to 'タイムライン', timeline_articles_path %></li>
    <li><%= link_to 'お気に入り', favorite_articles_articles_path %></li>
    <li><%= link_to 'タグ', tagged_articles_articles_path %></li>
  <% end %>
</ul>
<div>ランキング</div>
<ul>
  <li><%= link_to '月間ランキング', monthly_ranking_articles_path %></li>
</ul>

app/views/articles/_articles.html.erb
<div class="mb-5">
  <% articles.each do |article| %>
    <article class="user-article">
      <header class="article-header">
        <div class="article-header-left">
          <%= link_to user_path(article.user) do %>
            <% if article.user.image_attachment %>
              <%= image_tag article.user.index_display_image, class: 'rounded rounded-circle img-fluid border border-dark' if article.user.image.attached? %>
            <% elsif article.user.auth_image %>
              <img src="<%= article.user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark" width="30" height="30">
            <% else %>
              <img src="<%= gravatar_url(article.user, { size: 20 }) %>">
            <% end %>
          <% end %>
          <%= link_to article.user.name, user_path(article.user) %>
        </div>
        <p class="ml-4 article-header-right"><%= l article.created_at %> に投稿</p>
        <p class="ml-4"><i class="fas fa-heart mr-1"></i><%= article.liked_users.count %></p>
      </header>
      <h2><a href="<%= article_path(article) %>"><%= article.title %></a></h2>
      <div class="tag-container mt-3">
        <p>タグ</p>
        <ul class="tag-field">
          <% article.attached_tags.each do |tag| %>
            <li class="mr-2"><%= link_to tag.name, tag %></li>
          <% end %>
        </ul>
      </div>
     
    </article>
  <% end %>
</div>

app/views/articles/_comment.html.erb
<div class="comment-container">
  <div class="comment-container_list my-3">
    <h2 class="m-2">コメント一覧</h2>
    <ul>
      <% comments.each do |comment| %>
        <li>
          <%= link_to user_path(comment.user) do %>
            <% if comment.user.image_attachment %>
              <%= image_tag comment.user.index_display_image, class: 'rounded rounded-circle img-fluid border border-dark' %>
            <% elsif comment.user.auth_image %>
              <img src="<%= comment.user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark" width="30" height="30">
            <% else %>
              <img src="<%= gravatar_url(current_user, { size: 30 }) %>">
            <% end %>
          <% end %>
          <%= link_to comment.user.name, user_path(comment.user) %>
          <p class="mt-1"><%= comment.comment_content %></p>
        </li>  
      <% end %>
    </ul>
  </div>
  <div class="comment-container_post mt-3">
    <%= form_with(model: [article, @comment], local: true, method: :post) do |f| %>
      <%= render 'layouts/error_messages', model: @comment %>
      <div class="form-group">
        <%= f.label :comment_content, 'コメント', class: 'd-block' %>
        <%= f.text_area :comment_content %>
      </div>
      <%= f.hidden_field :article_id, value: article.id %>

      <%= f.submit 'コメントする', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/articles/_favorite.html.erb
<%= form_with(model: current_user.favorites.build) do |f| %>
  <%= hidden_field_tag :article_id, article.id %>
  <%= f.submit 'Like!', class: 'btn btn-primary' %>
<% end %>

app/views/articles/_report_spam.html.erb
<div class="report-spam-container">
  <% if logged_in? %>
    <% if !current_user.report_spam?(article) %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            <span class="fa fa-ellipsis-h fa-lg"></span>
          </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item">
                <%= form_with(model: current_user.report_spams.build, local: true) do |f| %>
                  <%= hidden_field_tag :article_id, article.id %>
                  <%= f.submit '問題がある記事を報告する', class: 'btn btn-danger' %>
                <% end %>
              </li>
              <li class="dropdown-item">
                <% if current_user.admin? %>
                  <%= link_to "記事を削除する", admin_article_path(article), method: :delete, class: 'btn btn-secondary' %>
                <% end %>
              </li>
            </ul>
        </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/articles/_unfavorite.html.erb
<%= form_with(model: current_user.favorites.find_by(article_id: article.id), method: :delete) do |f| %>
  <%= hidden_field_tag :article_id, article.id %>
  <%= f.submit 'Unlike', class: 'btn btn-danger' %>
<% end %>

app/views/articles/favorite_articles.html.erb
<div class="home">
  <div class="toppage-main px-2 mt-5">
    <div class="toppage-main_inner">
      <div class="toppage-main_start ml-2">
        <%= render 'article_feed' %>
      </div>
      <div class="toppage-main_end">
          <div class="toppage-main_end-header">
            <div><span class="fa fa-laugh-wink"></span></div>
            <p>お気に入り</p>
          </div>
          <div>
            <%= render 'articles/articles', articles: @articles %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="home">
  <% if current_user == nil %>
    <div class="toppage-hero">
      <div class="toppage-hero_inner">
        <div class="toppage-hero_start">
          <h1>SoccerPub</h1>
          <p>SoccerPubは、サッカーに関する話題を共有し、自分の応援するチームのファンと繋がれるアプリです。</p>
        </div>
        <div class="toppage-hero_end">
          <%= render 'users/signup_form', user: @user %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="toppage-main px-2 mt-5">
    <div class="toppage-main_inner">
      <div class="toppage-main_start ml-2">
        <%= render 'articles/article_feed' %>
      </div>
      <div class="toppage-main_end">
        <% if @search %>
          <div class="search-result">
            <p class="mb-1"><%= @search %>の検索結果</p>
            <ul class="nav nav-tabs">
              <div><span class="fa fa-laugh-wink"></span></div>
              <li class="active ml-2"><%= @count_search_result %>件見つかりました</li>
            </ul>
          </div>
        <% else %>
          <div class="toppage-main_end-header">
            <div><span class="fa fa-laugh-wink"></span></div>
            <p>最新</p>
          </div>
        <% end %>
        <div>
          <%= render 'articles/articles', articles: @articles %>
        </div>
        <%= paginate @articles %>
      </div>
    </div>
  </div>
</div>

app/views/articles/monthly_ranking.html.erb
<div class="home">
  <div class="toppage-main px-2 mt-5">
    <div class="toppage-main_inner">
      <div class="toppage-main_start ml-2">
        <%= render 'article_feed' %>
      </div>
      <div class="toppage-main_end">
          <div class="toppage-main_end-header">
            <div><span class="fa fa-laugh-wink"></span></div>
            <p>月間ランキング</p>
          </div>
          <div>
            <%= render 'articles/articles', articles: @monthly_ranking_articles %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="new-articles mt-3">
  <%= form_with(model: @form, local: true) do |f| %>
    <div class="form-group bg-primary">
      <%= f.text_field :title, class: 'form-control', placeholder: 'タイトル' %>
    </div>
    <div class="form-group bg-secondary">
      <%= f.text_field :tag_names, class: 'form-control', placeholder: 'タグ' %>
    </div>
    <div class="form-group">
      <%= f.label :content, '内容' %>
      <%= f.rich_text_area :content %>
    </div>
    <div>
      <%= f.submit '投稿する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="show-wrapper">
  <div class="wrapper-container">
    <div class="wrapper-container-article">
      <div class="wrapper-container-article-header">
        <div class="article-show-header">
          <div class="header_info mb-3">
            <div class="author mr-3">
              <div class="mr-2">
                <%= link_to user_path(@user) do %>
                  <% if @user.image_attachment %>
                    <%= image_tag @user.navbar_display_image, class: 'rounded rounded-circle img-fluid border border-dark' if @user.image.attached? %>
                  <% elsif @user.auth_image %>
                    <img src="<%= @user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark" width="40" height="40">
                  <% else %>
                    <img src="<%= gravatar_url(@user, { size: 20 }) %>">
                  <% end %>
                <% end %>
              </div>
              <div><a href="<%= user_path(@user) %>"><%= @user.name %></a></div>
            </div>
            <div class="header_time ml-3"><span><%= l @article.created_at %> に投稿</span></div>
          </div>
        </div>
        <h3 class="article-show-header-title"><%= @article.title %></h3>
        <div class="tag-and-like">
          <div class="tag-container">
            <p>タグ</p>
            <ul class="tag-field">
              <% @article.attached_tags.each do |tag| %>
                <li class="mr-2"><%= link_to tag.name, tag %></li>
              <% end %>
            </ul>
          </div>
          <div class="likes">
            <p class="mr-5"><%= @count_favorites %> likes!</p>
            <%= render 'articles/report_spam', article: @article %>
          </div>
        </div>
      </div>
      <section class="wrapper-container-article-content border-top py-3">
        <div class="mb-3">内容</div>
        <div><%= @article.content %></div>
        <div class="mt-3">
          <%= render 'favorites/favorite_button', article: @article %>
        </div>
      </section>
      <div class="wrapper-container-article-footer border-top py-3">
        <div class="author mr-3">
          <div class="mr-2">
            <% if @user.image_attachment %>
              <%= image_tag @user.navbar_display_image, class: 'rounded rounded-circle img-fluid border border-dark' if @user.image.attached? %>
            <% elsif @user.auth_image %>
              <img src="<%= @user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark" width="40" height="40">
            <% else %>
              <img src="<%= gravatar_url(@user, { size: 20 }) %>">
            <% end %>
          </div>
          <div><a href="<%= user_path(@user) %>"><%= @user.name %></a></div>
        </div>
        <div class="mt-3">
          <%= render 'users/follow_form', user: @user %>
        </div>
      </div>
    </div>
      <%= render 'articles/comment', article: @article, comments: @comments, comment: @comment %>
  </div>
</div>
<script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/articles/tagged_articles.html.erb
<div class="home">
  <div class="toppage-main px-2 mt-5">
    <div class="toppage-main_inner">
      <div class="toppage-main_start ml-2">
        <%= render 'article_feed' %>
      </div>
      <div class="toppage-main_end">
        <div class="toppage-main_end-header">
          <div><span class="fa fa-laugh-wink"></span></div>
          <p>タグ</p>
        </div>
        <div>
          <%= render 'articles/articles', articles: @articles %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/timeline.html.erb
<div class="home">
  <div class="toppage-main px-2 mt-5">
    <div class="toppage-main_inner">
      <div class="toppage-main_start ml-2">
        <%= render 'article_feed' %>
      </div>
      <div class="toppage-main_end">
          <div class="toppage-main_end-header">
            <div><span class="fa fa-laugh-wink"></span></div>
            <p>タイムライン</p>
          </div>
          <div>
            <%= render 'articles/articles', articles: @articles %>
          </div>
      </div>
    </div>
  </div>
</div>