config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
  get 'signup', to: 'users#new'
  resources :users, param: :friendly_id, only: %i[show create edit update destroy] do
    member do
      get :followings
      get :followers
      get :favorite_articles
      get :introduction
    end
  end
  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :articles, only: [:destroy] do
      collection do
        get :spams
      end
    end 
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  
  resources :articles, only: %i[show new create destroy] do
    collection do
      get :timeline
      get :favorite_articles
      get :tagged_articles
      get :monthly_ranking
    end

    resources :comments, only: [:create]
  end
  
  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :tags, only: [:show]
  resources :tag_follows, only: %i[create destroy]
  resources :searches, only: [:index]
  resources :report_spams, only: %i[create destroy]
  resources :oembed, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email, :friendly_id_nil
  before_create :create_activation_digest
  has_secure_password
  has_one :image_attachment, -> { where(name: 'image') }, class_name: "ActiveStorage::Attachment", as: :record, inverse_of: :record, dependent: false
  has_one :image_blob, through: :image_attachment, class_name: "ActiveStorage::Blob", source: :blob
  has_one_attached :image
  has_many :articles, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy, inverse_of: 'follow'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  
  has_many :report_spams, dependent: :destroy
  has_many :reported_spam_articles, through: :report_spams, source: :article
  
  has_many :tag_follows, dependent: :destroy
  has_many :following_tags, through: :tag_follows, source: :tag

  has_many :comments, dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 20 }
  validates :image, image: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, email: true
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  validates :friendly_id, friendly_id: true

  def follow(other_user)
    return if self == other_user

    relationships.find_or_create_by(follow_id: other_user.id)
  end
  
  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end
  
  def following?(other_user)
    followings.include?(other_user)
  end
  
  def favorite(article)
    favorites.find_or_create_by(article_id: article.id)
  end
  
  def unfavorite(article)
    favorite = favorites.find_by(article_id: article.id)
    favorite&.destroy
  end
  
  def favorite?(article)
    favorite_articles.include?(article)
  end
  
  def report_spam(article)
    report_spams.find_or_create_by(article_id: article.id)
  end
  
  def report_spam?(article)
    reported_spam_articles.include?(article)
  end
  
  def tag_follow(tag)
    tag_follows.find_or_create_by(tag_id: tag.id)
  end

  def tag_unfollow(tag)
    tag_follow = tag_follows.find_by(tag_id: tag.id)
    tag_follow&.destroy
  end
  
  def tag_following?(tag)
    following_tags.include?(tag)
  end
  
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end

    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  def display_image
    image.variant(resize_to_limit: [200, 200])
  end
  
  def index_display_image
    image.variant(resize_to_limit: [30, 30])
  end
  
  def navbar_display_image
    image.variant(resize_to_limit: [50, 50])
  end

  def to_param
    friendly_id ? "@#{friendly_id}" : super() 
  end
    
  private   

  def downcase_email
    self.email = email.downcase
  end

  def friendly_id_nil
    self.friendly_id = nil if friendly_id.blank?
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include CommonActions
  before_action :admin_user
  
  def index
    @users = User.all.page(params[:page]).eager_load(image_attachment: :blob)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CommonActions
  before_action :require_user_logged_in, only: %i[edit update destroy followings followers favorite_articles introduction]
  before_action :set_user, only: %i[show edit update destroy followings followers favorite_articles introduction]
  before_action :correct_user, only: %i[edit update destroy]
  
  def new
    @user = User.new
  end

  def show
    @articles = @user.articles.page(params[:page]).preload(:attached_tags)
    counts(@user)
  end

  def create
    @user = User.new(user_params)
    @user.image.attach(params[:user][:image])
    if @user.save
      @user.send_activation_email
      flash[:info] = 'アカウントを有効化するため、メールをご確認ください。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました。'
      render :new
    end
  end

  def edit
    counts(@user)
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザーを更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー更新に失敗しました。'
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to root_path
  end
  
  def followings
    @followings = @user.followings.page(params[:page]).eager_load(image_attachment: :blob)
    counts(@user)
  end
  
  def followers
    @followers = @user.followers.page(params[:page]).eager_load(image_attachment: :blob)
    counts(@user)
  end
  
  def favorite_articles
    @articles = @user.favorite_articles.page(params[:page]).order(created_at: :desc).preload(:attached_tags, user: { image_attachment: :blob })
    counts(@user)
  end

  def introduction
    @articles = @user.favorite_articles.page(params[:page])
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :friendly_id, :image, :email, :password, :password_confirmation, :introduction)
  end

  def set_user
    if params[:friendly_id].chr == '@'
      params[:friendly_id].slice!(0)
      @user = User.find_by(friendly_id: params[:friendly_id])
    else
      @user = User.find(params[:friendly_id])
    end
  end

  def correct_user
    return if current_user == @user

    redirect_to root_url
  end
      
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end

  def correct_user?(user)
    current_user == user
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.relationships.build) do |f| %>
  <%= hidden_field_tag :follow_id, user.id %>
  <%= f.submit 'フォローする', class: 'btn btn-primary' %>
<% end %>

app/views/users/_follow_form.html.erb
<% if logged_in? %>
  <% unless current_user == user %>
    <div id="follow_form">
      <% if current_user.following?(user) %>
        <%= render "users/unfollow", user: user %>
      <% else %>
        <%= render "users/follow", user: user %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form-group">
      <%= f.label :name, 'ユーザー名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :friendly_id, 'ユーザーID' %>
      <%= f.text_field :friendly_id, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :image, 'ユーザー画像' %>
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png",  class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, '確認' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
  <% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.relationships.find_by(follow_id: user.id), method: :delete) do |f| %>
  <%= hidden_field_tag :follow_id, user.id %>
  <%= f.submit 'フォローを外す', class: 'btn btn-danger' %>
<% end %>

app/views/users/_user_card.html.erb
<div class="card py-3">
      <div class="card-body">
        <div class="text-center">
          <% if @user.image_attachment || @user.auth_image %>
            <%= image_tag user.display_image, class: 'rounded rounded-circle img-fluid border border-dark' if user.image.attached? %>
            <img src="<%= user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark">
          <% else %>
            <img src="<%= gravatar_url(@user) %>">
          <% end %>
        </div>
        <h4 class="card-title text-center mt-3"><%= user.name %></h4>
        <div class="card-body_flex mt-5">
          <p><a href="<%= user_path(user) %>">投稿</a></p>
          <p><a href="<%= followings_user_path(user) %>"><span id="followings_count" class="badge badge-secondary"><%= count_followings %></span>フォロー</a></p>
          <p><a href="<%= followers_user_path(user) %>"><span id="followers_count" class="badge badge-secondary"><%= count_followers %></span>フォロワー</a></p>
        </div>
        <% if correct_user?(user) %>
          <div class="text-center mt-3">
            <%= link_to 'プロフィールを編集する', edit_user_path(user) %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="mt-3 text-center">
      <%= render 'follow_form', user: user %>
    </div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media border-bottom mb-2">
        <div class="media-body">
          <div class="mb-2">
            <%= link_to user_path(user), class: 'mr-2' do %>
              <% if user.image_attachment %>
                <%= image_tag user.navbar_display_image, class: 'rounded rounded-circle img-fluid border border-dark' if user.image.attached? %>
              <% elsif user.auth_image %> 
                <img src="<%= user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark" width="40" height="40">
              <% else %>
                <img src="<%= gravatar_url(current_user, { size: 30 }) %>">
              <% end %>
              <span class="h5"><%= user.name %></span>
            <% end %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <%= render 'user_card', user: @user, count_followers: @count_followers, count_followings: @count_followings %>
  </div>
  <div class="col-md-7">
    <h2><%= @user.name %>のプロフィール</h2>
    
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :friendly_id, 'ユーザーID' %>
        <%= f.text_field :friendly_id, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :image, '画像' %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, '自己紹介' %>
        <%= f.text_field :introduction, class: 'form-control' %>
      </div>
      
      <%= f.submit '更新する', class: 'btn btn-primary btn-block' %>
      <%= link_to 'パスワードの変更はこちらから', new_password_reset_path, class: 'btn btn-danger btn-block' %>
    <% end %>
    <script type="text/javascript">
      $("#user_image").bind("change", function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
          alert("画像ファイルは5MBよりも小さいものにしてください");
          $("#user_image").val("");
        }
      });
    </script>
  </div>
</div>

app/views/users/favorite_articles.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <%= render 'user_card', user: @user, count_followers: @count_followers, count_followings: @count_followings %>
  </div>
  <div class="col-md-7">
    <div class="title mb-2">
      <div class="box"></div>
      <div class="ml-4">ユーザー詳細</div>
    </div>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">My記事</a></li>
      <li class="nav-item"><a href="<%= favorite_articles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favorite_articles_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= introduction_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(introduction_user_path(@user)) %>">自己紹介</a></li>
      </ul>
    <%= render 'articles/articles', articles: @articles, user: @user %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <%= render 'user_card', user: @user, count_followers: @count_followers, count_followings: @count_followings %>
  </div>
  <div class="col-md-7">
    <div class="title mb-2">
      <div class="box"></div>
      <div class="ml-4">フォロワー</div>
    </div>
    <div>
      <%= render 'users', users: @followers %>
    </div>
  </div>
  
  
  
  
  

app/views/users/followings.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <%= render 'user_card', user: @user, count_followers: @count_followers, count_followings: @count_followings %>
  </div>
  <div class="col-md-7">
    <div class="title mb-2">
      <div class="box"></div>
      <div class="ml-4">フォロー</div>
    </div>
    <div>
      <%= render 'users', users: @followings %>
    </div>
  </div>
  
  
  
  
  

app/views/users/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/introduction.html.erb
<div class="row mt-4">
  <div class="col-md-5">
    <%= render 'user_card', user: @user, count_followers: @count_followers, count_followings: @count_followings %>
  </div>
  <div class="col-md-7">
    <div class="title mb-2">
      <div class="box"></div>
      <div class="ml-4">ユーザー詳細</div>
    </div>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">My記事</a></li>
      <li class="nav-item"><a href="<%= favorite_articles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favorite_articles_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= introduction_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(introduction_user_path(@user)) %>">自己紹介</a></li>
    </ul>
    
    <p><%= @user.introduction %></p>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup-container">
  <div class="text-center mb-4 pt-5">
    <h1>SoccerPubへようこそ！</h1>
  </div>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= render 'users/signup_form', user: @user %>
      <script type="text/javascript">
        $("#user_image").bind("change", function() {
          var size_in_megabytes = this.files[0].size/1024/1024;
          if (size_in_megabytes > 5) {
            alert("画像ファイルは5MBよりも小さいものにしてください");
            $("#user_image").val("");
          }
        });
      </script>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render 'user_card', user: @user, count_followers: @count_followers, count_followings: @count_followings %>
  </div>
  <div class="col-md-7">
    <div class="title mb-2">
      <div class="box"></div>
      <div class="ml-4">ユーザー詳細</div>
    </div>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">My記事</a></li>
      <li class="nav-item"><a href="<%= favorite_articles_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favorite_articles_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="#" class="nav-link">自己紹介</a></li>
    </ul>
    <%= render 'articles/articles', articles: @articles, user: @user %>
  </div>
</div>