config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  
  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
  get 'signup', to: 'users#new'
  resources :users, param: :friendly_id, only: %i[show create edit update destroy] do
    member do
      get :followings
      get :followers
      get :favorite_articles
      get :introduction
    end
  end
  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :articles, only: [:destroy] do
      collection do
        get :spams
      end
    end 
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  
  resources :articles, only: %i[show new create destroy] do
    collection do
      get :timeline
      get :favorite_articles
      get :tagged_articles
      get :monthly_ranking
    end

    resources :comments, only: [:create]
  end
  
  resources :relationships, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :tags, only: [:show]
  resources :tag_follows, only: %i[create destroy]
  resources :searches, only: [:index]
  resources :report_spams, only: %i[create destroy]
  resources :oembed, only: [:create]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">SoccerPub</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end navbar-content" id="navbarSupportedContent">
      <div class="fuzzy_search mr-5">
        <%= form_tag(searches_path, method: :get) do %>
          <%= text_field_tag :search, "", placeholder: 'タイトルで検索' %>
          <%= submit_tag '検索', size: 30*30 %>
        <% end %>
      </div>
      <p><%= link_to '投稿する', new_article_path %></p>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <% if current_user.image_attachment %>
                <%= image_tag current_user.navbar_display_image, class: 'rounded rounded-circle img-fluid border border-dark' %>
              <% elsif current_user.auth_image %>
                <img src="<%= current_user.auth_image %>" class="rounded rounded-circle img-fluid border border-dark" width="40" height="40">
              <% else %>
                <img src="<%= gravatar_url(current_user, { size: 30 }) %>">
              <% end %>
            </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
                <% if current_user.admin %>
                  <li class="dropdown-item"><%= link_to 'ユーザー一覧', admin_users_path %></li>
                  <li class="dropdown-item"><%= link_to 'スパム報告一覧', spams_admin_articles_path %></li>
                <% end %>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Soccerpub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>